// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQXLN3Q0LuozxfHjeSuSWXgA8OrTKRLaI',
    appId: '1:618328460689:web:82afc86abf0d9c71ccde30',
    messagingSenderId: '618328460689',
    projectId: 'flutter-tiktok-95041',
    authDomain: 'flutter-tiktok-95041.firebaseapp.com',
    storageBucket: 'flutter-tiktok-95041.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLIVNzSjUItjM0FCkNVIYxWo9AXQ1gNk8',
    appId: '1:618328460689:android:ea19652364d41af4ccde30',
    messagingSenderId: '618328460689',
    projectId: 'flutter-tiktok-95041',
    storageBucket: 'flutter-tiktok-95041.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB2hTKcmF64BQNTDrEM68pHkMczbqUatM',
    appId: '1:618328460689:ios:dde2f99f14a145c6ccde30',
    messagingSenderId: '618328460689',
    projectId: 'flutter-tiktok-95041',
    storageBucket: 'flutter-tiktok-95041.appspot.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB2hTKcmF64BQNTDrEM68pHkMczbqUatM',
    appId: '1:618328460689:ios:dfb2f47327ce5e25ccde30',
    messagingSenderId: '618328460689',
    projectId: 'flutter-tiktok-95041',
    storageBucket: 'flutter-tiktok-95041.appspot.com',
    iosBundleId: 'com.example.example.RunnerTests',
  );
}
